var ARAP=function(a,l,f){this.m=a.length;this.G=math.zeros(2*this.m,2*this.m);this.H=math.zeros(2*this.m,2*this.m);this.GpB;this.verts=a;this.tris=l;this.handles=f;this.computeG();this.computeGpB()};ARAP.prototype.X=function(a,l,f){return math.subset(a,math.index(l,f))};ARAP.prototype.Z=function(a,l,f,m){var d=this.X;a.subset(math.index(l,f),d(a,l,f)+m);l!=f&&a.subset(math.index(f,l),d(a,f,l)+m)};ARAP.prototype.Zs=function(a,l,f,m){var d=this.X;a.subset(math.index(l,f),d(a,l,f)+m)};
ARAP.prototype.xind=function(a){return 2*a};ARAP.prototype.yind=function(a){return 2*a+1};
ARAP.prototype.computeG=function(){for(var a=this.G,l=this.H,f=this.tris,m=this.verts,d=this.xind,h=this.yind,t=this.X,p=0;p<f.length;p++){var q=[{v0:f[p].a,v1:f[p].b,v2:f[p].c},{v0:f[p].b,v1:f[p].c,v2:f[p].a},{v0:f[p].c,v1:f[p].a,v2:f[p].b}];f[p].sarray=[];f[p].tarray=[];for(var s=0;3>s;s++){var n=q[s].v0,g=q[s].v1,b=q[s].v2,c=m[n],k=m[g],e=m[b],r=k.x-c.x,k=k.y-c.y,r=math.inv([[r,k],[k,-r]]),c=math.matrix([[e.x-c.x],[e.y-c.y]]),e=math.multiply(r,c),c=t(e,0,0),e=t(e,1,0);f[p].sarray[s]=c;f[p].tarray[s]=
e;this.Z(a,d(n),d(n),(1-c)*(1-c));this.Z(a,d(n),d(g),(1-c)*c);this.Z(a,d(n),h(g),(1-c)*e);this.Z(a,d(n),h(n),-(1-c)*e);this.Z(a,d(n),d(b),-(1-c));this.Z(a,d(g),d(g),c*c);this.Z(a,d(g),h(g),c*e);this.Z(a,d(g),h(n),-c*e);this.Z(a,d(g),d(b),-c);this.Z(a,h(g),h(g),e*e);this.Z(a,h(g),h(n),-e*e);this.Z(a,h(g),d(b),-e);this.Z(a,h(n),h(n),e*e);this.Z(a,h(n),d(b),e);this.Z(a,d(b),d(b),1);this.Z(a,h(n),h(n),(1-c)*(1-c));this.Z(a,h(n),d(g),-(1-c)*e);this.Z(a,h(n),d(n),(1-c)*e);this.Z(a,h(n),h(g),(1-c)*c);this.Z(a,
h(n),h(b),-(1-c));this.Z(a,d(g),d(g),e*e);this.Z(a,d(g),d(n),-e*e);this.Z(a,d(g),h(g),-e*c);this.Z(a,d(g),h(b),e);this.Z(a,d(n),d(n),e*e);this.Z(a,d(n),h(g),c*e);this.Z(a,d(n),h(b),-e);this.Z(a,h(g),h(g),c*c);this.Z(a,h(g),h(b),-c);this.Z(a,h(b),h(b),1);this.Z(l,d(g),d(g),1);this.Z(l,d(n),d(n),1);this.Z(l,d(g),d(n),-1);this.Z(l,h(g),h(g),1);this.Z(l,h(n),h(n),1);this.Z(l,h(g),h(n),-1)}c=f[p].sarray[0];e=f[p].tarray[0];f[p].Finv=math.inv(math.matrix([[2+2*(1-c)*(1-c)+2*e*e,0,2*(1-c)*c-2*e*e,2*(1-c)*
e+2*c*e],[0,2+2*e*e+2*(1-c)*(1-c),-2*c*e-2*e*(1-c),-2*e*e+2*c*(1-c)],[2*c*(1-c)-2*e*e,-2*c*e-2*e*(1-c),2+2*c*c+2*e*e,0],[2*(1-c)*e+2*c*e,-2*e*e+2*c*(1-c),0,2+2*e*e+2*c*c]]))}};ARAP.prototype.computeGpB=function(){var a=this.G,l=this.m,f=2*l-2*this.handles,m=math.subset(a,math.index([0,f],[0,f])),d=math.subset(a,math.index([0,f],[f,2*l])),a=math.subset(a,math.index([f,2*l],[0,f])),m=math.add(m,math.transpose(m)),d=math.add(d,math.transpose(a));this.GpB=math.multiply(math.inv(m),d)};
ARAP.prototype.distBtw=function(a,l){var f=a.cx||a.x,m=a.cy||a.y,d=l.cx||l.x,h=l.cy||l.y;return math.sqrt((f-d)*(f-d)+(m-h)*(m-h))};
ARAP.prototype.computeNewVerts=function(a){for(var l=this.handles,f=this.m,m=this.tris,d=this.GpB,h=this.H,t=this.xind,p=this.yind,q=this.X,s=this.distBtw,n=this.verts,g=[],b=0;b<n.length;b++)g[b]={cx:n[b].x,cy:n[b].y};for(var c in a)g[c].cx=a[c].x,g[c].cy=a[c].y;a=math.zeros(2*l,1);for(b=0;b<l;b++)this.Zs(a,2*b,0,g[f-l+b].cx),this.Zs(a,2*b+1,0,g[f-l+b].cy);a=math.multiply(d,a);for(b=0;b<f-l;b++)g[b].cx=-q(a,2*b,0),g[b].cy=-q(a,2*b+1,0);a=[];for(b=0;b<m.length;b++){var k=g[m[b].a],e=g[m[b].b],r=g[m[b].c],
d=m[b].sarray[0];c=m[b].tarray[0];k=math.matrix([[-2*k.cx-2*(1-d)*r.cx-2*c*r.cy],[-2*k.cy+2*c*r.cx-2*(1-d)*r.cy],[-2*e.cx-2*d*r.cx+2*c*r.cy],[-2*e.cy-2*c*r.cx-2*d*r.cy]]);k=math.multiply(m[b].Finv,k);a[b]={a:{cx:-q(k,0,0),cy:-q(k,1,0)},b:{cx:-q(k,2,0),cy:-q(k,3,0)},c:{cx:-q(k,0,0)+d*(-q(k,2,0)- -q(k,0,0))+c*(-q(k,3,0)- -q(k,1,0)),cy:-q(k,1,0)+d*(-q(k,3,0)- -q(k,1,0))-c*(-q(k,2,0)- -q(k,0,0))}}}for(b=0;b<m.length;b++)k=a[b],d=s(a[b].a,a[b].b)/s(n[m[b].a],n[m[b].b]),c=(k.a.cx+k.b.cx+k.c.cx)/3,k=(k.a.cy+
k.b.cy+k.c.cy)/3,a[b].a.cx=c+(a[b].a.cx-c)/d,a[b].a.cy=k+(a[b].a.cy-k)/d,a[b].b.cx=c+(a[b].b.cx-c)/d,a[b].b.cy=k+(a[b].b.cy-k)/d,a[b].c.cx=c+(a[b].c.cx-c)/d,a[b].c.cy=k+(a[b].c.cy-k)/d;d=math.zeros(1,2*f);for(b=0;b<m.length;b++)for(c=[{v0:m[b].a,v1:m[b].b,i:"a",j:"b"},{v0:m[b].b,v1:m[b].c,i:"b",j:"c"},{v0:m[b].c,v1:m[b].a,i:"c",j:"a"}],k=0;3>k;k++){var e=c[k].v0,r=c[k].v1,s=a[b][c[k].i],u=a[b][c[k].j];this.Zs(d,0,t(r),-2*u.cx);this.Zs(d,0,t(r),2*s.cx);this.Zs(d,0,t(e),2*u.cx);this.Zs(d,0,t(e),-2*
s.cx);this.Zs(d,0,p(r),-2*u.cy);this.Zs(d,0,p(r),2*s.cy);this.Zs(d,0,p(e),2*u.cy);this.Zs(d,0,p(e),-2*s.cy)}a=math.zeros(2*l,1);for(b=0;b<l;b++)this.Zs(a,2*b,0,g[f-l+b].cx),this.Zs(a,2*b+1,0,g[f-l+b].cy);l=this.handles;p=2*f-2*l;t=math.subset(h,math.index([0,p],[0,p]));m=math.subset(h,math.index([0,p],[p,2*f]));h=math.subset(h,math.index([p,2*f],[0,p]));s=math.subset(d,math.index(0,[0,p]));t=math.add(t,math.transpose(t));m=math.add(m,math.transpose(h));h=math.inv(t);m=math.multiply(m,a);t=math.multiply(h,
math.transpose(s));a=math.add(math.multiply(h,m),t);for(b=0;b<f-l;b++)g[b].cx=-q(a,2*b,0),g[b].cy=-q(a,2*b+1,0);for(b=0;b<g.length;b++)n[b].x=g[b].cx,n[b].y=g[b].cy;return g};